name: kicad-exporter
description: Export KiCad 7.0 files to various formats
author: Parthiv Shah
branding:
  icon: 'code'
  color: 'blue'
  
inputs:
  out-files:
    description: |-
      Comma-separated or newline-separated list of output file formats.
        - `sch_pdf` for Schematic PDF
        - `pcb_pdf` for PCB PDF
        - `png` for PCB (3D) PNG
        - `stl` for PCB (3D) STL
        - `step` for PCB (3D) STEP

    required: true

runs:
  using: 'node20'
  main: 'dist/index.js'
