name: STEP Converter asdasd
inputs:
  step-file:
    required: true
  out-file:
    description: >
      Choose one of the following file types:
      - stl
      - png
      - jpg
    required: true

runs:
  using: "composite"
    steps:
      - name: Convert STEP
        id: convert-file
        run: ${{ github.action_path }}/converter.sh "${{ github.action_path }}/mayo-config.ini" "${{ inputs.step-file }}" "${{ inputs.out-file }}"
        shell: bash
